### PR TITLE
Fixed commandMan init reflection

### PR DESCRIPTION
**Pull request by marvhus**
I fixed the commandMan init reflection so it will successfully add the command classes to the array of commands

### CODE REVIEW

**Comment by KMatias123** [comment]
remove the .idea/ files and add them to .gitignore

**Comment by marvhus** [comment]
.gitignore should now be set up correctly to ignore the IntelliJ stuff and extra Java stuff

**Comment by KMatias123** [comment]
you have iml files in the module dir too

**Comment by KMatias123** [comment]
also ./target

**Review by KMatias123 — CHANGES_REQUESTED** [review]
remove le iml file in the module & remove the build files, then i'm fine with it

**Comment by KMatias123** [comment]
oop now it's fine

**Pull request merged**
